In [1]:
import numpy as np

In [2]:
f1 = np.loadtxt('climate_data_station1.csv',delimiter=',')
f1

array([[ 25.,  76.,  99.],
       [ 39.,  65.,  70.],
       [ 59.,  45.,  77.],
       ...,
       [ 95., 100.,  66.],
       [ 75.,  97.,  24.],
       [ 87.,  59.,  81.]])

In [3]:
f2 = np.loadtxt('climate_data_station2.csv',delimiter=',')
f2

array([[ 93.,  41.,  94.],
       [ 81.,  47.,  98.],
       [ 65.,  71.,  91.],
       ...,
       [ 57.,  91.,  27.],
       [ 51.,  92.,  64.],
       [100.,  32.,  82.]])

In [4]:
f = np.concatenate((f1,f2))
f

array([[ 25.,  76.,  99.],
       [ 39.,  65.,  70.],
       [ 59.,  45.,  77.],
       ...,
       [ 57.,  91.,  27.],
       [ 51.,  92.,  64.],
       [100.,  32.,  82.]])

In [5]:
f3 = np.loadtxt('climate_data_station3.csv',delimiter=',')
f3

array([[82., 21., 40.],
       [76., 76., 93.],
       [47., 24., 81.],
       ...,
       [68., 59., 74.],
       [49., 81., 28.],
       [44., 27., 27.]])

In [6]:
f4 = np.loadtxt('climate_data_station4.csv',delimiter=',')
f4

array([[38., 46., 21.],
       [68., 75., 33.],
       [29., 91., 68.],
       ...,
       [97., 43., 47.],
       [94., 90., 96.],
       [74., 66., 87.]])

In [7]:
f5 = np.loadtxt('climate_data_station5.csv',delimiter=',')
f5

array([[57., 98., 28.],
       [51., 51., 22.],
       [50., 79., 20.],
       ...,
       [62., 34., 83.],
       [98., 72., 23.],
       [79., 47., 46.]])

In [8]:
f6 = np.loadtxt('climate_data_station6.csv',delimiter=',')
f6

array([[ 27.,  49.,  71.],
       [ 50.,  77.,  22.],
       [ 91.,  30.,  87.],
       ...,
       [ 53.,  67.,  60.],
       [ 34.,  33.,  71.],
       [100.,  26.,  77.]])

In [9]:
f7 = np.loadtxt('climate_data_station7.csv',delimiter=',')
f7

array([[45., 75., 73.],
       [45., 61., 73.],
       [33., 98., 53.],
       ...,
       [44., 71., 21.],
       [50., 93., 76.],
       [83., 87., 56.]])

In [10]:
f8 = np.loadtxt('climate_data_station8.csv',delimiter=',')
f8

array([[97., 58., 60.],
       [70., 53., 96.],
       [40., 34., 57.],
       ...,
       [85., 68., 34.],
       [72., 73., 32.],
       [80., 31., 61.]])

In [11]:
f9 = np.loadtxt('climate_data_station9.csv',delimiter=',')
f9

array([[ 71.,  81.,  29.],
       [ 46.,  71.,  44.],
       [ 77.,  45., 100.],
       ...,
       [ 47.,  91.,  86.],
       [ 90.,  99.,  96.],
       [ 40.,  46.,  78.]])

In [12]:
f10 = np.loadtxt('climate_data_station10.csv',delimiter=',')
f10

array([[85., 51., 88.],
       [47., 66., 95.],
       [59., 95., 90.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [13]:
#concatinating all the array from file 1 to 10

f = np.concatenate((f1,f2,f3,f4,f5,f6,f7,f8,f9,f10))
f

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

# w1 = 0.3, w2 = 0.2, w3 =0.5
# formula ---> yield_of_corp  = w1 * temperature + w2 * rainfall + w3 * humidity


In [14]:
#temperature calculation
temp = f[:,0]
temp

array([25., 39., 59., ..., 99., 70., 92.])

In [15]:
temp_cal = 0.3*temp
temp_cal

array([ 7.5, 11.7, 17.7, ..., 29.7, 21. , 27.6])

In [16]:
rainfall = f[:,1]
rainfall

array([76., 65., 45., ..., 62., 71., 39.])

In [17]:
rainfall_cal =0.2*rainfall
rainfall_cal

array([15.2, 13. ,  9. , ..., 12.4, 14.2,  7.8])

In [18]:
humidity = f[:,2]
humidity

array([99., 70., 77., ..., 58., 91., 76.])

In [19]:
humidity_cal = 0.5*humidity
humidity_cal

array([49.5, 35. , 38.5, ..., 29. , 45.5, 38. ])

In [20]:
yield_of_crop = temp_cal + rainfall_cal + humidity_cal
yield_of_crop

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [21]:
result=np.stack((temp_cal,rainfall_cal,humidity_cal,yield_of_crop),axis=1)
result

array([[ 7.5, 15.2, 49.5, 72.2],
       [11.7, 13. , 35. , 59.7],
       [17.7,  9. , 38.5, 65.2],
       ...,
       [29.7, 12.4, 29. , 71.1],
       [21. , 14.2, 45.5, 80.7],
       [27.6,  7.8, 38. , 73.4]])

IndexError: index 3 is out of bounds for axis 1 with size 3